version: '2'
services:
  app:
    build: .
    volumes_from:
      - volumes_data
      
  nginx:
    image: "nginx:alpine"
    ports:
     - "80:80"
    volumes_from:
      - volumes_data
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  redis:
    image: "redis:alpine"

  volumes_data:
    image: tianon/true
    volumes:
      - ./app:/var/www/html
